# Generated by Django 3.0 on 2021-06-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(max_length=255, unique=True)),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_type', models.CharField(max_length=60)),
                ('goods_price', models.CharField(max_length=40)),
                ('goods_num', models.CharField(max_length=10)),
                ('goods_state', models.CharField(default='', max_length=50)),
                ('on_shelves', models.BooleanField(default=False)),
                ('is_show', models.BooleanField(default=False)),
            ],
        ),
    ]
