# Generated by Django 3.0 on 2021-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('goods_type', models.CharField(max_length=30)),
                ('goods_price', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=6)),
                ('user', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
